spring.application.name=auth-service
server.port=4005

# Use the variables injected by Docker Compose
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driverClassName=org.postgresql.Driver

# Hibernate & SQL settings
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.sql.init.mode=${SPRING_SQL_INIT_MODE:always}
# Wait for Hibernate to create the table before running data.sql
spring.jpa.defer-datasource-initialization=true