services:
  # 1. DATABASE
  db:
    image: postgres:15-alpine
    container_name: patient-service-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - medical-network

  # 2. KAFKA BROKER
  kafka:
    image: apache/kafka:latest
    container_name: kafka-broker
    restart: on-failure 
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
    networks:
      - medical-network

  # 3. BILLING SERVICE (Consumer & gRPC Server)
  billing-service:
    build: ./billing-service
    container_name: billing-service-app
    ports:
      - "4001:4001"
      - "9001:9001"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
    depends_on:
      - kafka
    networks:
      - medical-network

  # 4. ANALYTICS SERVICE (Consumer)
  analytics-service:
    build: ./analytics-service
    container_name: analytics-service-app
    ports:
      - "4002:4002"
    environment:
      # Use the variable from your .env here
      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
    depends_on:
      - kafka
    networks:
      - medical-network

  # 5. PATIENT SERVICE (Producer & gRPC Client)
  patient-service:
    build: ./patient-service
    container_name: patient-service-app
    restart: on-failure
    ports:
      - "4000:4000"
      - "5005:5005"
    environment:
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      SPRING_DATASOURCE_URL: jdbc:postgresql://patient-service-db:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_DATASOURCE_DRIVER: org.postgresql.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      BILLING_SERVICE_HOST: billing-service-app
      BILLING_SERVICE_PORT: 9001
    depends_on:
      - db
      - kafka
      - billing-service
    networks:
      - medical-network

networks:
  medical-network:
    driver: bridge