services:
  db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432" # Database usually stays 5432
    networks:
      - medical-network

  billing-service:
    build:
      context: ./billing-service
      dockerfile: Dockerfile
    container_name: billing-service-app
    ports:
      - "${BILLING_REST_PORT}:${BILLING_REST_PORT}"
      - "${BILLING_GRPC_PORT}:${BILLING_GRPC_PORT}"
    environment:
      SERVER_PORT: ${BILLING_REST_PORT}
      GRPC_SERVER_PORT: ${BILLING_GRPC_PORT}
    networks:
      - medical-network

  patient-service:
    build:
      context: ./patient-service
      dockerfile: Dockerfile
    container_name: patient-service-app
    ports:
      - "${PATIENT_PORT}:${PATIENT_PORT}"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${JPA_STRATEGY}
      SPRING_DATASOURCE_DRIVER: org.postgresql.Driver
      # Service-to-service communication
      BILLING_SERVICE_HOST: billing-service
      BILLING_SERVICE_PORT: ${BILLING_GRPC_PORT}
    depends_on:
      - db
      - billing-service
    networks:
      - medical-network

networks:
  medical-network:
    driver: bridge