server:
  port: 4004

spring:
  cloud:
    gateway:
      routes:
        # Route for Auth Service
        - id: auth-service-route
          # Use the variable from Docker Compose
          uri: ${AUTH_SERVICE_URL:http://auth-service:4005}
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        # Route for Patient Service
        - id: patient-service-route
          uri: ${PATIENT_SERVICE_URL:http://patient-service:4000}
          predicates:
            - Path=/api/patients/**
          filters:
            - StripPrefix=1
            - JwtValidation

        # Swagger Docs for Patients
        - id: api-docs-patient-route
          uri: ${PATIENT_SERVICE_URL:http://patient-service:4000}
          predicates:
            - Path=/api-docs/patients
          filters:
            - RewritePath=/api-docs/patients,/v3/api-docs

        # Swagger Docs for Auth
        - id: api-docs-auth-route
          uri: ${AUTH_SERVICE_URL:http://auth-service:4005}
          predicates:
            - Path=/api-docs/auth
          filters:
            - RewritePath=/api-docs/auth,/v3/api-docs