apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: healthcare
type: Opaque
# stringData lets you write plain text; K8s base64-encodes it automatically
stringData:
  PATIENT_DB_USER:     "admin"
  PATIENT_DB_PASSWORD: "my_super_secret_password"
  AUTH_DB_USER:        "auth_admin"
  AUTH_DB_PASSWORD:    "auth_password"
  JWT_SECRET:          "ThisIsMySuperSecretKeyForSigningMyTokens1234567890"
