---
# ── Deployment ───────────────────────────────────────────────────────────────
apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service
  namespace: healthcare
  labels:
    app: patient-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-service
  template:
    metadata:
      labels:
        app: patient-service
    spec:
      containers:
        - name: patient-service
          image: patient-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_DATASOURCE_URL_PATIENT
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: PATIENT_DB_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: PATIENT_DB_PASSWORD
            - name: SPRING_DATASOURCE_DRIVER
              value: "org.postgresql.Driver"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_JPA_HIBERNATE_DDL_AUTO
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_KAFKA_BOOTSTRAP_SERVERS
            # gRPC client — reaches billing-service K8s Service on port 9001
            - name: BILLING_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: BILLING_SERVICE_HOST
            - name: BILLING_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: BILLING_SERVICE_PORT
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 4000
            initialDelaySeconds: 90
            periodSeconds: 15
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 4000
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3

---
# ── Service (ClusterIP) ───────────────────────────────────────────────────────
apiVersion: v1
kind: Service
metadata:
  name: patient-service
  namespace: healthcare
spec:
  selector:
    app: patient-service
  ports:
    - port: 4000
      targetPort: 4000
