spring.application.name=patient-service
server.port=4000

# Try to find Docker env variables. If they don't exist, use H2 fallbacks.
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:patientdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin_viewer}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.datasource.driverClassName=${SPRING_DATASOURCE_DRIVER:org.h2.Driver}

# JPA Settings
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
# Show SQL only in dev
spring.jpa.show-sql=true

# H2 Console (Only works when using H2)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Logging
logging.level.root=INFO
logging.level.com.pm=DEBUG