spring.application.name=analytics-service
server.port=4002

# Tell it where Kafka is
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

# Tell it how to handle the binary data
spring.kafka.consumer.group-id=analytics-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer